(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Vehicle version: 0.23.0+dev *)
(*  - Rocq version: 9.0.0 *)

From mathcomp Require Import all_boot.
From mathcomp Require Import all_algebra.
From mathcomp Require Import all_reals.
Require Import vehicle.tensor.
Open Scope ring_scope.
Open Scope order_scope.

Parameter R : realType.

Definition UnnormalisedInputVector : Type := 'nT[R]_(6%N :: nil).

Definition InputVector : Type := 'nT[R]_(6%N :: nil).

Definition conc : 'I_6%N := 0.

Definition temp : 'I_6%N := 1.

Definition wbc : 'I_6%N := 2.

Definition age : 'I_6%N := 3.

Definition weight : 'I_6%N := 4.

Definition sex : 'I_6%N := 5.

Definition OutputVector : Type := 'nT[R]_(1%N :: nil).

Parameter pk : InputVector -> OutputVector.

Definition normpk (x : UnnormalisedInputVector) : OutputVector := pk x.

Definition Ka : 'nT[R]_(nil) := const_t (5 : R).

Axiom Ka_pos : const_t (0 : R) < Ka.

Definition Ke : 'nT[R]_(nil) := const_t (4 : R).

Axiom Ke_pos : const_t (0 : R) < Ke.

Axiom Ke_n_Ka : Ka != Ke.

Definition Vd : 'nT[R]_(nil) := const_t (10 : R).

Axiom Vd_pos : const_t (0 : R) < Vd.

Definition C_safe : 'nT[R]_(nil) := const_t (30 : R).

Axiom C_safe_pos : const_t (0 : R) < C_safe.

Definition max_conc : 'nT[R]_(nil) := const_t (2231435513 / 10000000000 : R).

Axiom max_conc_pos : const_t (0 : R) < max_conc.

Definition safeInput (x : InputVector) : Prop := ((const_t (0 : R) <= x^^conc) /\ (x^^conc <= C_safe)) /\ (((const_t (73 / 2 : R) <= x^^temp) /\ (x^^temp <= const_t (40 : R))) /\ (((const_t (15 / 2 : R) <= x^^wbc) /\ (x^^wbc <= const_t (20 : R))) /\ (((const_t (18 : R) <= x^^age) /\ (x^^age <= const_t (89 : R))) /\ (((const_t (50 : R) <= x^^weight) /\ (x^^weight <= const_t (100 : R))) /\ ((const_t (0 : R) <= x^^sex) /\ (x^^sex <= const_t (1 : R))))))).

Definition safeOutput (x : InputVector) : Prop := (x^^conc + (max_conc * (normpk x)^^0)) <= C_safe.

Axiom safe : forall x, safeInput x -> safeOutput x.
