(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Rocq version: 9.0.0 *)
(*  - Vehicle version: 0.22.0 *)

Require Import mathcomp.ssreflect.ssrbool.
Require Import mathcomp.algebra.ssralg.
Require Import mathcomp.ssreflect.ssrnat.
Require Import mathcomp.ssreflect.eqtype.
Require Import mathcomp.ssreflect.order.
Require Import mathcomp.ssreflect.fintype.
Require Import mathcomp.ssreflect.seq.
Require Import mathcomp.algebra.zmodp.
Require Import mathcomp.reals.reals.
Require Import vehicle.tensor.
Open Scope ring_scope.
Open Scope order_scope.

Parameter R : realType.

Definition UnnormalisedInputVector : Type := 'nT[R]_(6%N :: nil).

Definition InputVector : Type := 'nT[R]_(6%N :: nil).

Definition conc : 'I_6%N := 0.

Definition temp : 'I_6%N := 1.

Definition wbc : 'I_6%N := 2.

Definition age : 'I_6%N := 3.

Definition weight : 'I_6%N := 4.

Definition sex : 'I_6%N := 5.

Definition OutputVector : Type := 'nT[R]_(1%N :: nil).

Parameter pk : InputVector -> OutputVector.

Definition normpk (x : UnnormalisedInputVector) : OutputVector := pk x.

Definition safeOutput (x : InputVector) : Prop := (const_t (0 : R) <= (((normpk x)^^0 / const_t (30 : R)) + x^^conc)) /\ ((((normpk x)^^0 / const_t (30 : R)) + x^^conc) <= const_t (30 : R)).

Definition unhealthyInput (x : InputVector) : Prop := ((const_t (0 : R) <= x^^conc) /\ (x^^conc <= const_t (30 : R))) /\ (((const_t (38 : R) <= x^^temp) /\ (x^^temp <= const_t (40 : R))) /\ (((const_t (12 : R) <= x^^wbc) /\ (x^^wbc <= const_t (20 : R))) /\ (((const_t (18 : R) <= x^^age) /\ (x^^age <= const_t (89 : R))) /\ (((const_t (50 : R) <= x^^weight) /\ (x^^weight <= const_t (100 : R))) /\ (x^^sex == const_t (1 : R)) \/ (x^^sex == const_t (0 : R)))))).

Definition unhealthyOutput (x : InputVector) : Prop := (const_t (10 : R) <= (((normpk x)^^0 / const_t (30 : R)) + x^^conc)) /\ ((((normpk x)^^0 / const_t (30 : R)) + x^^conc) <= const_t (30 : R)).

Axiom unhealthy : forall x, unhealthyInput x -> unhealthyOutput x.

Definition healthyInput (x : InputVector) : Prop := ((const_t (0 : R) <= x^^conc) /\ (x^^conc <= const_t (30 : R))) /\ (((const_t (36 : R) <= x^^temp) /\ (x^^temp <= const_t (38 : R))) /\ (((const_t (4 : R) <= x^^wbc) /\ (x^^wbc <= const_t (12 : R))) /\ (((const_t (18 : R) <= x^^age) /\ (x^^age <= const_t (89 : R))) /\ (((const_t (50 : R) <= x^^weight) /\ (x^^weight <= const_t (100 : R))) /\ (x^^sex == const_t (1 : R)) \/ (x^^sex == const_t (0 : R)))))).

Definition healthyOutput (x : InputVector) : Prop := (normpk x)^^0 == const_t (0 : R).

Axiom healthy : forall x, healthyInput x -> healthyOutput x.

Axiom safe : forall x, healthyInput x \/ unhealthyInput x -> safeOutput x.

Definition nextTemp (x : InputVector) : 'nT[R]_(nil) := let y := normpk x in (((x^^temp + const_t (2 / 25 : R)) - (const_t (1 / 200 : R) * x^^conc)) + (y^^0 / const_t (30 : R))) - (const_t (3 / 25 : R) * x^^temp - const_t (37 : R)).

Axiom tempDecr : forall x, unhealthyInput x -> nextTemp x <= (x^^temp - const_t (1 / 100 : R)).

Axiom tempStable : forall x, healthyInput x -> (const_t (36 : R) <= nextTemp x) /\ (nextTemp x <= const_t (38 : R)).