(* WARNING: This file was generated automatically by Vehicle *)
(* and should not be modified manually! *)
(* Metadata: *)
(*  - Vehicle version: 0.23.0+dev *)
(*  - Rocq version: 9.0.0 *)

From Stdlib Require Import Reals.
From mathcomp Require Import all_boot.
From mathcomp Require Import all_algebra.
From mathcomp Require Import all_reals.
From mathcomp Require Import Rstruct.
Require Import vehicle.tensor.
Open Scope ring_scope.
Open Scope order_scope.

Notation R := Rdefinitions.R.

Definition UnnormalisedInputVector : Type := 'nT[R]_(6%N :: nil).

Definition InputVector : Type := 'nT[R]_(6%N :: nil).

Definition conc : 'I_6%N := 0.

Definition temp : 'I_6%N := 1.

Definition wbc : 'I_6%N := 2.

Definition age : 'I_6%N := 3.

Definition weight : 'I_6%N := 4.

Definition sex : 'I_6%N := 5.

Definition OutputVector : Type := 'nT[R]_(1%N :: nil).

Parameter pk : InputVector -> OutputVector.

Definition normpk (x : UnnormalisedInputVector) : OutputVector := pk x.

Definition Ka : 'nT[R]_(nil) := const_t (9 / 2 : R).

Axiom Ka_pos : const_t (0 : R) < Ka.

Definition Ke : 'nT[R]_(nil) := const_t (7 / 2 : R).

Axiom Ke_pos : const_t (0 : R) < Ke.

Axiom Ke_n_Ka : Ka != Ke.

Definition Vd : 'nT[R]_(nil) := const_t (10 : R).

Axiom Vd_pos : const_t (0 : R) < Vd.

Definition C_safe : 'nT[R]_(nil) := const_t (30 : R).

Axiom C_safe_pos : const_t (0 : R) < C_safe.

Definition ttd : 'nT[R]_(nil) := const_t (2 : R).

Axiom ttd_pos : const_t (0 : R) < ttd.

Definition Ka_over : 'nT[R]_(nil) := const_t (807 / 2500 : R).

Definition Ka_under : 'nT[R]_(nil) := const_t (3227 / 10000 : R).

Definition Ke_over : 'nT[R]_(nil) := const_t (83 / 200 : R).

Definition Ke_under : 'nT[R]_(nil) := const_t (4149 / 10000 : R).

Definition root_over : 'nT[R]_(nil) := const_t (1257 / 5000 : R).

Axiom root_over_ttd : root_over < ttd.

Definition safeInput (x : InputVector) : Prop := ((const_t (0 : R) <= x^^conc) /\ (x^^conc <= C_safe)) /\ (((const_t (73 / 2 : R) <= x^^temp) /\ (x^^temp <= const_t (40 : R))) /\ (((const_t (15 / 2 : R) <= x^^wbc) /\ (x^^wbc <= const_t (20 : R))) /\ (((const_t (18 : R) <= x^^age) /\ (x^^age <= const_t (89 : R))) /\ (((const_t (50 : R) <= x^^weight) /\ (x^^weight <= const_t (100 : R))) /\ ((const_t (0 : R) <= x^^sex) /\ (x^^sex <= const_t (1 : R))))))).

Definition safeOutput (x : InputVector) : Prop := let y := ((normpk x)^^0 * Ka) / (Vd * Ka - Ke) in if Ka < Ke then (x^^conc + (y * Ke_under - Ka_over)) <= C_safe else (x^^conc + (y * Ke_over - Ka_under)) <= C_safe.

Axiom safe : forall x, safeInput x -> safeOutput x.

Definition nonNegOutput (x : InputVector) : Prop := const_t (0 : R) <= (normpk x)^^0.

Axiom nonNeg : forall x, safeInput x -> nonNegOutput x.
